version: '3.5'

services:
  php:
    container_name: php_server
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      #XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./:/appdata/www
      #./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa